### ISSUE TITLE
Passing `--url` to `status` CLI command overrides URL of underlying request to API

### ISSUE THREAD

**Issue by benedfit** [BCDevOps/gh-deploy#9]
**Describe the bug**
When using the CLI, setting `--url` results in a request to that URL, rather than the correct Github API endpoint

**To Reproduce**
1. `npx @bcgov/gh-deploy ... --url "http://test.com"`
2. Console output throws an error. `request.url` can be seen as `http://test.com`
3. `request.body.log_url` is set correctly

**Expected behavior**
`request.url` should remain pointing to the Github API

**Comment by benedfit** [comment]
FYI I'd be very happy to submit a PR to fix this

**Comment by patricksimonian** [comment]
oops! Yeah i'd be happy to accept a pr. Thank you!
